/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as GoIdRouteImport } from './routes/go/$id'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardPaginaRouteImport } from './routes/dashboard/pagina'
import { Route as DashboardModelosRouteImport } from './routes/dashboard/modelos'
import { Route as DashboardFinanceiroRouteImport } from './routes/dashboard/financeiro'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardPreviewLinkIdRouteImport } from './routes/dashboard/preview/$linkId'
import { Route as DashboardModelsModelIdRouteImport } from './routes/dashboard/models/$modelId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const GoIdRoute = GoIdRouteImport.update({
  id: '/go/$id',
  path: '/go/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaginaRoute = DashboardPaginaRouteImport.update({
  id: '/pagina',
  path: '/pagina',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardModelosRoute = DashboardModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceiroRoute = DashboardFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPreviewLinkIdRoute = DashboardPreviewLinkIdRouteImport.update({
  id: '/preview/$linkId',
  path: '/preview/$linkId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardModelsModelIdRoute = DashboardModelsModelIdRouteImport.update({
  id: '/models/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/modelos': typeof DashboardModelosRoute
  '/dashboard/pagina': typeof DashboardPaginaRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/go/$id': typeof GoIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/models/$modelId': typeof DashboardModelsModelIdRoute
  '/dashboard/preview/$linkId': typeof DashboardPreviewLinkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/modelos': typeof DashboardModelosRoute
  '/dashboard/pagina': typeof DashboardPaginaRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/go/$id': typeof GoIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/models/$modelId': typeof DashboardModelsModelIdRoute
  '/dashboard/preview/$linkId': typeof DashboardPreviewLinkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/financeiro': typeof DashboardFinanceiroRoute
  '/dashboard/modelos': typeof DashboardModelosRoute
  '/dashboard/pagina': typeof DashboardPaginaRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/go/$id': typeof GoIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/models/$modelId': typeof DashboardModelsModelIdRoute
  '/dashboard/preview/$linkId': typeof DashboardPreviewLinkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/financeiro'
    | '/dashboard/modelos'
    | '/dashboard/pagina'
    | '/dashboard/settings'
    | '/go/$id'
    | '/dashboard/'
    | '/dashboard/models/$modelId'
    | '/dashboard/preview/$linkId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/financeiro'
    | '/dashboard/modelos'
    | '/dashboard/pagina'
    | '/dashboard/settings'
    | '/go/$id'
    | '/dashboard'
    | '/dashboard/models/$modelId'
    | '/dashboard/preview/$linkId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/financeiro'
    | '/dashboard/modelos'
    | '/dashboard/pagina'
    | '/dashboard/settings'
    | '/go/$id'
    | '/dashboard/'
    | '/dashboard/models/$modelId'
    | '/dashboard/preview/$linkId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  GoIdRoute: typeof GoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/go/$id': {
      id: '/go/$id'
      path: '/go/$id'
      fullPath: '/go/$id'
      preLoaderRoute: typeof GoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pagina': {
      id: '/dashboard/pagina'
      path: '/pagina'
      fullPath: '/dashboard/pagina'
      preLoaderRoute: typeof DashboardPaginaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/modelos': {
      id: '/dashboard/modelos'
      path: '/modelos'
      fullPath: '/dashboard/modelos'
      preLoaderRoute: typeof DashboardModelosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/financeiro': {
      id: '/dashboard/financeiro'
      path: '/financeiro'
      fullPath: '/dashboard/financeiro'
      preLoaderRoute: typeof DashboardFinanceiroRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/preview/$linkId': {
      id: '/dashboard/preview/$linkId'
      path: '/preview/$linkId'
      fullPath: '/dashboard/preview/$linkId'
      preLoaderRoute: typeof DashboardPreviewLinkIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/models/$modelId': {
      id: '/dashboard/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/dashboard/models/$modelId'
      preLoaderRoute: typeof DashboardModelsModelIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardFinanceiroRoute: typeof DashboardFinanceiroRoute
  DashboardModelosRoute: typeof DashboardModelosRoute
  DashboardPaginaRoute: typeof DashboardPaginaRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardModelsModelIdRoute: typeof DashboardModelsModelIdRoute
  DashboardPreviewLinkIdRoute: typeof DashboardPreviewLinkIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardFinanceiroRoute: DashboardFinanceiroRoute,
  DashboardModelosRoute: DashboardModelosRoute,
  DashboardPaginaRoute: DashboardPaginaRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardModelsModelIdRoute: DashboardModelsModelIdRoute,
  DashboardPreviewLinkIdRoute: DashboardPreviewLinkIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  GoIdRoute: GoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
